[-COMMENT-:GLOBAL]
# MAKEFILE KEYWORDS FILE FOR CRIMSON EDITOR
# FIRST EDITED BY IGKANG, JUNE 10, 2003 
# updated by Luc FERRAN March 28, 2004

[KEYWORDS0:GLOBAL]
.SUFFIXES 

[KEYWORDS1:GLOBAL]
ifeq ifneq else endif ifdef ifndef export include define endef
addprefix notdir addsuffix
